name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - uses: aws-actions/setup-sam@v2

      - name: Build SAM Application
        run: |
          sam build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::886675821060:role/LambdaGitHubActionDeploymentRole
          role-session-name: github-action-sam-deploy-session
          aws-region: eu-west-1

      - name: Deploy SAM Application
        run: |
          sam deploy

